services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: go-rate-limiter
    entrypoint: sh ./.docker/entrypoint.dev.sh
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8080:8080
    networks:
      - go-rate-limiter
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: go-rate-limiter-redis
    ports:
      - 6379:6379
    networks:
      - go-rate-limiter

networks:
  go-rate-limiter:
    driver: bridge